- name: Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: installing nginx
      ansible.builtin.dnf:
            name: nginx
            state: present

    - name:  Placing expense conf file in nginx
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name:  deleting old nginx content
      ansible.builtin.file:
         path: /usr/share/nginx/html
         state: absent

    - name: Creating Nginx Content Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name:  Download frontend Code and Extract it
      ansible.builtin.get_url:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Starting Nginx Service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes

      






















#  source log.sh
#  echo installing nginx
#  dnf install nginx -y  >>$log
#  echo placing expenselog file
#  cp expense.conf /etc/nginx/default.d/expense.conf >>$log
#  echo enable nginx
#  systemctl enable nginx >>$log
#  echo starting nginx
#  systemctl start nginx >>$log
#  echo deleting old content
#  rm -rf /usr/share/nginx/html/* >>$log
#  echo downloading frontend code
#  curl -s -o /tmp/frontend.zip https://expense-artifacts.s3.amazonaws.com/frontend.zip >>$log
#  cd /usr/share/nginx/html >>$log
#  echo extracting frontend code
#  unzip /tmp/frontend.zip >>$log
#  systemctl restart nginx >>$log
